'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicioSoapAsmx
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VWInfoPeople", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class VWInfoPeople
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDPeopleField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecondNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentIDField As String
        
        Private TypeDocumentIDField As System.Nullable(Of Integer)
        
        Private BirthDateField As System.Nullable(Of Date)
        
        Private CountryIDField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrincipalPhoneField As String
        
        Private UpdateUpdField As System.Nullable(Of Date)
        
        Private CreateDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeDocumentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property IDPeople() As Integer
            Get
                Return Me.IDPeopleField
            End Get
            Set
                If (Me.IDPeopleField.Equals(value) <> true) Then
                    Me.IDPeopleField = value
                    Me.RaisePropertyChanged("IDPeople")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SecondName() As String
            Get
                Return Me.SecondNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SecondNameField, value) <> true) Then
                    Me.SecondNameField = value
                    Me.RaisePropertyChanged("SecondName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property DocumentID() As String
            Get
                Return Me.DocumentIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentIDField, value) <> true) Then
                    Me.DocumentIDField = value
                    Me.RaisePropertyChanged("DocumentID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property TypeDocumentID() As System.Nullable(Of Integer)
            Get
                Return Me.TypeDocumentIDField
            End Get
            Set
                If (Me.TypeDocumentIDField.Equals(value) <> true) Then
                    Me.TypeDocumentIDField = value
                    Me.RaisePropertyChanged("TypeDocumentID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property BirthDate() As System.Nullable(Of Date)
            Get
                Return Me.BirthDateField
            End Get
            Set
                If (Me.BirthDateField.Equals(value) <> true) Then
                    Me.BirthDateField = value
                    Me.RaisePropertyChanged("BirthDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property CountryID() As System.Nullable(Of Integer)
            Get
                Return Me.CountryIDField
            End Get
            Set
                If (Me.CountryIDField.Equals(value) <> true) Then
                    Me.CountryIDField = value
                    Me.RaisePropertyChanged("CountryID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Addres() As String
            Get
                Return Me.AddresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddresField, value) <> true) Then
                    Me.AddresField = value
                    Me.RaisePropertyChanged("Addres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property PrincipalPhone() As String
            Get
                Return Me.PrincipalPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrincipalPhoneField, value) <> true) Then
                    Me.PrincipalPhoneField = value
                    Me.RaisePropertyChanged("PrincipalPhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property UpdateUpd() As System.Nullable(Of Date)
            Get
                Return Me.UpdateUpdField
            End Get
            Set
                If (Me.UpdateUpdField.Equals(value) <> true) Then
                    Me.UpdateUpdField = value
                    Me.RaisePropertyChanged("UpdateUpd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=10)>  _
        Public Property CreateDate() As System.Nullable(Of Date)
            Get
                Return Me.CreateDateField
            End Get
            Set
                If (Me.CreateDateField.Equals(value) <> true) Then
                    Me.CreateDateField = value
                    Me.RaisePropertyChanged("CreateDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property TypeDocument() As String
            Get
                Return Me.TypeDocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeDocumentField, value) <> true) Then
                    Me.TypeDocumentField = value
                    Me.RaisePropertyChanged("TypeDocument")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DTPeople", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DTPeople
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDPeopleField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecondNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentIDField As String
        
        Private TypeDocumentIDField As System.Nullable(Of Integer)
        
        Private BirthDateField As System.Nullable(Of Date)
        
        Private CountryIDField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrincipalPhoneField As String
        
        Private UpdateUpdField As System.Nullable(Of Date)
        
        Private CreateDateField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property IDPeople() As Integer
            Get
                Return Me.IDPeopleField
            End Get
            Set
                If (Me.IDPeopleField.Equals(value) <> true) Then
                    Me.IDPeopleField = value
                    Me.RaisePropertyChanged("IDPeople")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SecondName() As String
            Get
                Return Me.SecondNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SecondNameField, value) <> true) Then
                    Me.SecondNameField = value
                    Me.RaisePropertyChanged("SecondName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property DocumentID() As String
            Get
                Return Me.DocumentIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentIDField, value) <> true) Then
                    Me.DocumentIDField = value
                    Me.RaisePropertyChanged("DocumentID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property TypeDocumentID() As System.Nullable(Of Integer)
            Get
                Return Me.TypeDocumentIDField
            End Get
            Set
                If (Me.TypeDocumentIDField.Equals(value) <> true) Then
                    Me.TypeDocumentIDField = value
                    Me.RaisePropertyChanged("TypeDocumentID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property BirthDate() As System.Nullable(Of Date)
            Get
                Return Me.BirthDateField
            End Get
            Set
                If (Me.BirthDateField.Equals(value) <> true) Then
                    Me.BirthDateField = value
                    Me.RaisePropertyChanged("BirthDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property CountryID() As System.Nullable(Of Integer)
            Get
                Return Me.CountryIDField
            End Get
            Set
                If (Me.CountryIDField.Equals(value) <> true) Then
                    Me.CountryIDField = value
                    Me.RaisePropertyChanged("CountryID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Addres() As String
            Get
                Return Me.AddresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddresField, value) <> true) Then
                    Me.AddresField = value
                    Me.RaisePropertyChanged("Addres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property PrincipalPhone() As String
            Get
                Return Me.PrincipalPhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrincipalPhoneField, value) <> true) Then
                    Me.PrincipalPhoneField = value
                    Me.RaisePropertyChanged("PrincipalPhone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property UpdateUpd() As System.Nullable(Of Date)
            Get
                Return Me.UpdateUpdField
            End Get
            Set
                If (Me.UpdateUpdField.Equals(value) <> true) Then
                    Me.UpdateUpdField = value
                    Me.RaisePropertyChanged("UpdateUpd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=10)>  _
        Public Property CreateDate() As System.Nullable(Of Date)
            Get
                Return Me.CreateDateField
            End Get
            Set
                If (Me.CreateDateField.Equals(value) <> true) Then
                    Me.CreateDateField = value
                    Me.RaisePropertyChanged("CreateDate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DTDocumentsType", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DTDocumentsType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private TypeDocumentIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeDocumentField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property TypeDocumentID() As Integer
            Get
                Return Me.TypeDocumentIDField
            End Get
            Set
                If (Me.TypeDocumentIDField.Equals(value) <> true) Then
                    Me.TypeDocumentIDField = value
                    Me.RaisePropertyChanged("TypeDocumentID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property TypeDocument() As String
            Get
                Return Me.TypeDocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeDocumentField, value) <> true) Then
                    Me.TypeDocumentField = value
                    Me.RaisePropertyChanged("TypeDocument")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DTCountries", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DTCountries
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CountryIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CountryID() As Integer
            Get
                Return Me.CountryIDField
            End Get
            Set
                If (Me.CountryIDField.Equals(value) <> true) Then
                    Me.CountryIDField = value
                    Me.RaisePropertyChanged("CountryID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioSoapAsmx.Service1Soap")>  _
    Public Interface Service1Soap
        
        'CODEGEN: Generating message contract since element name GetAllPeopleViewResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAllPeopleView", ReplyAction:="*")>  _
        Function GetAllPeopleView(ByVal request As ServicioSoapAsmx.GetAllPeopleViewRequest) As ServicioSoapAsmx.GetAllPeopleViewResponse
        
        'CODEGEN: Generating message contract since element name GetDataAllPeopleResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDataAllPeople", ReplyAction:="*")>  _
        Function GetDataAllPeople(ByVal request As ServicioSoapAsmx.GetDataAllPeopleRequest) As ServicioSoapAsmx.GetDataAllPeopleResponse
        
        'CODEGEN: Generating message contract since element name GetPeopleByIDResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPeopleByID", ReplyAction:="*")>  _
        Function GetPeopleByID(ByVal request As ServicioSoapAsmx.GetPeopleByIDRequest) As ServicioSoapAsmx.GetPeopleByIDResponse
        
        'CODEGEN: Generating message contract since element name GetDTDocumentsTypeResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDTDocumentsType", ReplyAction:="*")>  _
        Function GetDTDocumentsType(ByVal request As ServicioSoapAsmx.GetDTDocumentsTypeRequest) As ServicioSoapAsmx.GetDTDocumentsTypeResponse
        
        'CODEGEN: Generating message contract since element name GetDTCountriesResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDTCountries", ReplyAction:="*")>  _
        Function GetDTCountries(ByVal request As ServicioSoapAsmx.GetDTCountriesRequest) As ServicioSoapAsmx.GetDTCountriesResponse
        
        'CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SetPeople", ReplyAction:="*")>  _
        Function SetPeople(ByVal request As ServicioSoapAsmx.SetPeopleRequest) As ServicioSoapAsmx.SetPeopleResponse
        
        'CODEGEN: Generating message contract since element name DeletetDTPeopleResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeletetDTPeople", ReplyAction:="*")>  _
        Function DeletetDTPeople(ByVal request As ServicioSoapAsmx.DeletetDTPeopleRequest) As ServicioSoapAsmx.DeletetDTPeopleResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllPeopleViewRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllPeopleView", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetAllPeopleViewRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetAllPeopleViewRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetAllPeopleViewRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllPeopleViewResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllPeopleViewResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetAllPeopleViewResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetAllPeopleViewResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetAllPeopleViewResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetAllPeopleViewResult() As ServicioSoapAsmx.VWInfoPeople
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAllPeopleViewResult() As ServicioSoapAsmx.VWInfoPeople)
            MyBase.New
            Me.GetAllPeopleViewResult = GetAllPeopleViewResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDataAllPeopleRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDataAllPeople", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetDataAllPeopleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetDataAllPeopleRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetDataAllPeopleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDataAllPeopleResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDataAllPeopleResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetDataAllPeopleResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetDataAllPeopleResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetDataAllPeopleResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDataAllPeopleResult() As ServicioSoapAsmx.DTPeople
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDataAllPeopleResult() As ServicioSoapAsmx.DTPeople)
            MyBase.New
            Me.GetDataAllPeopleResult = GetDataAllPeopleResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPeopleByIDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPeopleByID", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetPeopleByIDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetPeopleByIDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetPeopleByIDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public value As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal value As Integer)
            MyBase.New
            Me.value = value
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPeopleByIDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPeopleByIDResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetPeopleByIDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetPeopleByIDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetPeopleByIDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPeopleByIDResult As ServicioSoapAsmx.DTPeople
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPeopleByIDResult As ServicioSoapAsmx.DTPeople)
            MyBase.New
            Me.GetPeopleByIDResult = GetPeopleByIDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDTDocumentsTypeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDTDocumentsType", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetDTDocumentsTypeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetDTDocumentsTypeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetDTDocumentsTypeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDTDocumentsTypeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDTDocumentsTypeResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetDTDocumentsTypeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetDTDocumentsTypeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetDTDocumentsTypeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDTDocumentsTypeResult() As ServicioSoapAsmx.DTDocumentsType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDTDocumentsTypeResult() As ServicioSoapAsmx.DTDocumentsType)
            MyBase.New
            Me.GetDTDocumentsTypeResult = GetDTDocumentsTypeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDTCountriesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDTCountries", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetDTCountriesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetDTCountriesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetDTCountriesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDTCountriesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDTCountriesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.GetDTCountriesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.GetDTCountriesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetDTCountriesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDTCountriesResult() As ServicioSoapAsmx.DTCountries
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDTCountriesResult() As ServicioSoapAsmx.DTCountries)
            MyBase.New
            Me.GetDTCountriesResult = GetDTCountriesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetPeopleRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetPeople", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.SetPeopleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.SetPeopleRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetPeopleRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public item As ServicioSoapAsmx.DTPeople
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal item As ServicioSoapAsmx.DTPeople)
            MyBase.New
            Me.item = item
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetPeopleResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetPeopleResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.SetPeopleResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.SetPeopleResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetPeopleResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SetPeopleResult As ServicioSoapAsmx.DTPeople
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SetPeopleResult As ServicioSoapAsmx.DTPeople)
            MyBase.New
            Me.SetPeopleResult = SetPeopleResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeletetDTPeopleRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeletetDTPeople", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.DeletetDTPeopleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.DeletetDTPeopleRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DeletetDTPeopleRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public item As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal item As Integer)
            MyBase.New
            Me.item = item
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeletetDTPeopleResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeletetDTPeopleResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicioSoapAsmx.DeletetDTPeopleResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioSoapAsmx.DeletetDTPeopleResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DeletetDTPeopleResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DeletetDTPeopleResult As ServicioSoapAsmx.DTPeople
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DeletetDTPeopleResult As ServicioSoapAsmx.DTPeople)
            MyBase.New
            Me.DeletetDTPeopleResult = DeletetDTPeopleResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Service1SoapChannel
        Inherits ServicioSoapAsmx.Service1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioSoapAsmx.Service1Soap)
        Implements ServicioSoapAsmx.Service1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioSoapAsmx_Service1Soap_GetAllPeopleView(ByVal request As ServicioSoapAsmx.GetAllPeopleViewRequest) As ServicioSoapAsmx.GetAllPeopleViewResponse Implements ServicioSoapAsmx.Service1Soap.GetAllPeopleView
            Return MyBase.Channel.GetAllPeopleView(request)
        End Function
        
        Public Function GetAllPeopleView() As ServicioSoapAsmx.VWInfoPeople()
            Dim inValue As ServicioSoapAsmx.GetAllPeopleViewRequest = New ServicioSoapAsmx.GetAllPeopleViewRequest()
            inValue.Body = New ServicioSoapAsmx.GetAllPeopleViewRequestBody()
            Dim retVal As ServicioSoapAsmx.GetAllPeopleViewResponse = CType(Me,ServicioSoapAsmx.Service1Soap).GetAllPeopleView(inValue)
            Return retVal.Body.GetAllPeopleViewResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioSoapAsmx_Service1Soap_GetDataAllPeople(ByVal request As ServicioSoapAsmx.GetDataAllPeopleRequest) As ServicioSoapAsmx.GetDataAllPeopleResponse Implements ServicioSoapAsmx.Service1Soap.GetDataAllPeople
            Return MyBase.Channel.GetDataAllPeople(request)
        End Function
        
        Public Function GetDataAllPeople() As ServicioSoapAsmx.DTPeople()
            Dim inValue As ServicioSoapAsmx.GetDataAllPeopleRequest = New ServicioSoapAsmx.GetDataAllPeopleRequest()
            inValue.Body = New ServicioSoapAsmx.GetDataAllPeopleRequestBody()
            Dim retVal As ServicioSoapAsmx.GetDataAllPeopleResponse = CType(Me,ServicioSoapAsmx.Service1Soap).GetDataAllPeople(inValue)
            Return retVal.Body.GetDataAllPeopleResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioSoapAsmx_Service1Soap_GetPeopleByID(ByVal request As ServicioSoapAsmx.GetPeopleByIDRequest) As ServicioSoapAsmx.GetPeopleByIDResponse Implements ServicioSoapAsmx.Service1Soap.GetPeopleByID
            Return MyBase.Channel.GetPeopleByID(request)
        End Function
        
        Public Function GetPeopleByID(ByVal value As Integer) As ServicioSoapAsmx.DTPeople
            Dim inValue As ServicioSoapAsmx.GetPeopleByIDRequest = New ServicioSoapAsmx.GetPeopleByIDRequest()
            inValue.Body = New ServicioSoapAsmx.GetPeopleByIDRequestBody()
            inValue.Body.value = value
            Dim retVal As ServicioSoapAsmx.GetPeopleByIDResponse = CType(Me,ServicioSoapAsmx.Service1Soap).GetPeopleByID(inValue)
            Return retVal.Body.GetPeopleByIDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioSoapAsmx_Service1Soap_GetDTDocumentsType(ByVal request As ServicioSoapAsmx.GetDTDocumentsTypeRequest) As ServicioSoapAsmx.GetDTDocumentsTypeResponse Implements ServicioSoapAsmx.Service1Soap.GetDTDocumentsType
            Return MyBase.Channel.GetDTDocumentsType(request)
        End Function
        
        Public Function GetDTDocumentsType() As ServicioSoapAsmx.DTDocumentsType()
            Dim inValue As ServicioSoapAsmx.GetDTDocumentsTypeRequest = New ServicioSoapAsmx.GetDTDocumentsTypeRequest()
            inValue.Body = New ServicioSoapAsmx.GetDTDocumentsTypeRequestBody()
            Dim retVal As ServicioSoapAsmx.GetDTDocumentsTypeResponse = CType(Me,ServicioSoapAsmx.Service1Soap).GetDTDocumentsType(inValue)
            Return retVal.Body.GetDTDocumentsTypeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioSoapAsmx_Service1Soap_GetDTCountries(ByVal request As ServicioSoapAsmx.GetDTCountriesRequest) As ServicioSoapAsmx.GetDTCountriesResponse Implements ServicioSoapAsmx.Service1Soap.GetDTCountries
            Return MyBase.Channel.GetDTCountries(request)
        End Function
        
        Public Function GetDTCountries() As ServicioSoapAsmx.DTCountries()
            Dim inValue As ServicioSoapAsmx.GetDTCountriesRequest = New ServicioSoapAsmx.GetDTCountriesRequest()
            inValue.Body = New ServicioSoapAsmx.GetDTCountriesRequestBody()
            Dim retVal As ServicioSoapAsmx.GetDTCountriesResponse = CType(Me,ServicioSoapAsmx.Service1Soap).GetDTCountries(inValue)
            Return retVal.Body.GetDTCountriesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioSoapAsmx_Service1Soap_SetPeople(ByVal request As ServicioSoapAsmx.SetPeopleRequest) As ServicioSoapAsmx.SetPeopleResponse Implements ServicioSoapAsmx.Service1Soap.SetPeople
            Return MyBase.Channel.SetPeople(request)
        End Function
        
        Public Function SetPeople(ByVal item As ServicioSoapAsmx.DTPeople) As ServicioSoapAsmx.DTPeople
            Dim inValue As ServicioSoapAsmx.SetPeopleRequest = New ServicioSoapAsmx.SetPeopleRequest()
            inValue.Body = New ServicioSoapAsmx.SetPeopleRequestBody()
            inValue.Body.item = item
            Dim retVal As ServicioSoapAsmx.SetPeopleResponse = CType(Me,ServicioSoapAsmx.Service1Soap).SetPeople(inValue)
            Return retVal.Body.SetPeopleResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioSoapAsmx_Service1Soap_DeletetDTPeople(ByVal request As ServicioSoapAsmx.DeletetDTPeopleRequest) As ServicioSoapAsmx.DeletetDTPeopleResponse Implements ServicioSoapAsmx.Service1Soap.DeletetDTPeople
            Return MyBase.Channel.DeletetDTPeople(request)
        End Function
        
        Public Function DeletetDTPeople(ByVal item As Integer) As ServicioSoapAsmx.DTPeople
            Dim inValue As ServicioSoapAsmx.DeletetDTPeopleRequest = New ServicioSoapAsmx.DeletetDTPeopleRequest()
            inValue.Body = New ServicioSoapAsmx.DeletetDTPeopleRequestBody()
            inValue.Body.item = item
            Dim retVal As ServicioSoapAsmx.DeletetDTPeopleResponse = CType(Me,ServicioSoapAsmx.Service1Soap).DeletetDTPeople(inValue)
            Return retVal.Body.DeletetDTPeopleResult
        End Function
    End Class
End Namespace
